### ISSUE TITLE
Access to mail Session

### ISSUE THREAD

**Issue by brunorene** [nithril/smtp-connection-pool#1]
Hi,

When you create a SmtpConnectionFactoryBuilder you can create a inner Session that is not accessible from the outside. So when you want to create a new MimeMessage you can't reuse the Session created inside the Builder. I had to create a SmtpConnectionFactory directly and create the Session outside it in order to create new MimeMessages

Regards

**Comment by nithril** [comment]
Hi! 

The session is available through `SmtpConnectionFactory#getSession`. In my opinion it is more logical to access it using this method than through the builder that is not a reusable component

**Comment by nithril** [comment]
I have added [`ClosableSmtpConnection#getSession`](https://github.com/nithril/smtp-connection-pool/blob/master/src/main/java/org/nlab/smtp/transport/ClosableSmtpConnection.java#L23) and [`SmtpConnectionPool#getSession`](https://github.com/nithril/smtp-connection-pool/blob/master/src/main/java/org/nlab/smtp/pool/SmtpConnectionPool.java#L46-L48)

You will be able to do:

``` java
try (ClosableSmtpConnection transport = smtpConnectionPool.borrowObject()) {
    MimeMessage mimeMessage = new MimeMessage(transport.getSession());
    [...]
}
```
