### ISSUE TITLE
How do return borrowed objects?

### ISSUE THREAD

**Issue by ghost** [nithril/smtp-connection-pool#11]
Please tell me how do i return borrowed object, as i set max limit to "1"

config.setMaxTotal(1);

and after sending 1 mail i can't able to borrrow another object from pool.

**Comment by nithril** [comment]
See test example and the test case. Connection must be borrowed inside a try with resource statement:
```
try (ClosableSmtpConnection transport = smtpConnectionPool.borrowObject()) {
}
```
