### ISSUE TITLE
Release 1.2.3 version?

### ISSUE THREAD

**Issue by wryel** [nithril/smtp-connection-pool#14]
Any date to release 1.2.3 version to resolve issues from SmtpConnectionFactory#validateObject,activateObject,passivateObject,destroyObject that uses .isConnected() method?

**Comment by nithril** [comment]
Could you be more specific on the issue?

**Comment by wryel** [comment]
In version 1.2.2 multiple calls were being made in the method (many times for log only). On slow connections, this method takes time to return. I forked the project with the intention of fixing but when opening the code I noticed that the problem is already solved in the current snapshot version.

**Comment by nithril** [comment]
Thanks, I understand better your initial post. The 1.2.3 is released, it will be available in a couple of hours in maven central.
