### ISSUE TITLE
JavaMail 1.6.0 

### ISSUE THREAD

**Issue by d4nirod** [nithril/smtp-connection-pool#15]
I've upgraded to [JavaMail 1.6.0](https://github.com/javaee/javamail/releases/tag/JAVAMAIL-1_6_0) and so far no problems, any plans to update the project dependencies?

**Comment by nithril** [comment]
In one month or two, the time the 1.6 stabilizes and more issues are created in order to justify a new version.

**Comment by nithril** [comment]
@gmunisifreddy, I will upgrade to Javamail 1.6.1. Is it ok for you?

**Comment by gopi-gith** [comment]
Yes, upgrading Java mail is fine.
