### ISSUE TITLE
Multiple isConnected() calls on barrowObject is causing SMTP Server to raise 'possible SMTP attack' error 

### ISSUE THREAD

**Issue by gopi-gith** [nithril/smtp-connection-pool#16]
When we call borrowObject & testOnBorrow flag is enabled, the library is making two isConnected() calls - once in activateObject & again in  validateObject.  As each of these isConnected() calls send NOOP operations,   SMTP Servers are overwhelmed with number of NOOP operations they receive and flagging the client as 'possible SMTP attack(er)'.  We send several millions of emails everyday and two NOOP commands on every borrow operation is  causing issues. Also a we noticed degraded performance as [explained here on java mail code base](https://github.com/javaee/javamail/blob/aa5ccec0dfc992cebe882a77c15cef9850b61b0b/mail/src/main/java/com/sun/mail/smtp/SMTPTransport.java#L1449)

The way we are getting around this is to set testOnBorrow flag to false and relay on validating connection in activateObject method.

Should we consider modifying activteObject method not to call isConnected() method?

**Comment by nithril** [comment]
Yes you right, I will fix that in the next 3 days. Thanks for reporting.

**Comment by gopi-gith** [comment]
Thanks
