### ISSUE TITLE
New pull request proposal - Set expiry time for smtp connections

### ISSUE THREAD

**Issue by gopi-gith** [nithril/smtp-connection-pool#17]
SMTP Servers does not like when clients hang on to connections for very long time. They force clients to disconnect if the connection is held more than allowed amount of time.

In order to solve this problem, we extended the library to invalidate connections after a specified amount of time elapses. 

If this feature is helpful for others, we can submit a pull request with implementation and tests.

**Comment by nithril** [comment]
Could you please elaborate how your proposal is different from the [`DefaultEvictionPolicy`](https://commons.apache.org/proper/commons-pool/api-2.5.0/index.html?org/apache/commons/pool2/impl/DefaultEvictionPolicy.html) ?

**Comment by gopi-gith** [comment]
The DefaultEvictionPolicy seems to be based on idle time of a connection. What we would like to have is based on active time of a connection. Lets say if the SMTP Server does not allow connections to be open for more than 5 minutes, then we want to evict all connections in pool that are active for more than 5 minutes.

**Comment by nithril** [comment]
Thanks for the clarification, could you please submit the PR?

**Comment by gopi-gith** [comment]
on further investigation we found that this is one of the temporary hiccups in our infrastructure. we are not able to replicate the problem consistently. I'll investigate this further and get back to you with more information of the issue as well as the fix. please close this issue for now.
